// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP8xaX7HVLpEsUIAKsPHd0hq4FcfRxMU8',
    appId: '1:496310270602:web:ed165b134630d4c3a60b73',
    messagingSenderId: '496310270602',
    projectId: 'retailhub-ea728',
    authDomain: 'retailhub-ea728.firebaseapp.com',
    storageBucket: 'retailhub-ea728.appspot.com',
    measurementId: 'G-1MWLWQJFDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9RqMwWZSJ3MUl5h_GViaHZMzw7LdtjEQ',
    appId: '1:496310270602:android:07414d25ca8226efa60b73',
    messagingSenderId: '496310270602',
    projectId: 'retailhub-ea728',
    storageBucket: 'retailhub-ea728.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt5_sg01nuzMuuz6hXW_pjs7QBH7Wzp6Y',
    appId: '1:496310270602:ios:87b39a6f351b14d9a60b73',
    messagingSenderId: '496310270602',
    projectId: 'retailhub-ea728',
    storageBucket: 'retailhub-ea728.appspot.com',
    iosClientId: '496310270602-drq4ih2lsgj8ufvkq9i33tmndtvdrqk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttermeet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt5_sg01nuzMuuz6hXW_pjs7QBH7Wzp6Y',
    appId: '1:496310270602:ios:87b39a6f351b14d9a60b73',
    messagingSenderId: '496310270602',
    projectId: 'retailhub-ea728',
    storageBucket: 'retailhub-ea728.appspot.com',
    iosClientId: '496310270602-drq4ih2lsgj8ufvkq9i33tmndtvdrqk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttermeet',
  );
}
